---

- name: keystone | postdeploy 
  file: path=/var/log/keystone/keystone.log owner=keystone group=keystone mode=0644 state=touch
 
- name: kesytone | restart apache2 after deploy
  service: name=apache2 state=restarted 
  sudo: yes